__bible_prefix_map = {
   'gn':'Genesis',
   'ge':'Genesis',
   'gen':'Genesis',
   'gene':'Genesis',
   'genes':'Genesis',
   'genesi':'Genesis',
   'genesis':'Genesis',
   'ex':'Exodus',
   'exo':'Exodus',
   'exod':'Exodus',
   'exodu':'Exodus',
   'exodus':'Exodus',
   'lv':'Leviticus',
   'le':'Leviticus',
   'lev':'Leviticus',
   'levi':'Leviticus',
   'levit':'Leviticus',
   'leviti':'Leviticus',
   'levitic':'Leviticus',
   'leviticu':'Leviticus',
   'leviticus':'Leviticus',
   'nm':'Numbers',
   'nb':'Numbers',
   'nu':'Numbers',
   'num':'Numbers',
   'numb':'Numbers',
   'numbe':'Numbers',
   'number':'Numbers',
   'numbers':'Numbers',
   'de':'Deuteronomy',
   'deu':'Deuteronomy',
   'deut':'Deuteronomy',
   'deute':'Deuteronomy',
   'deuter':'Deuteronomy',
   'deutero':'Deuteronomy',
   'deuteron':'Deuteronomy',
   'deuterono':'Deuteronomy',
   'deuteronom':'Deuteronomy',
   'deuteronomy':'Deuteronomy',
   'jos':'Joshua',
   'josh':'Joshua',
   'joshu':'Joshua',
   'joshua':'Joshua',
   'judg':'Judges',
   'judge':'Judges',
   'judges':'Judges',
   'ru':'Ruth',
   'rut':'Ruth',
   'ruth':'Ruth',
   '1s':'1 Samuel',
   '1sa':'1 Samuel',
   '1sam':'1 Samuel',
   '1samu':'1 Samuel',
   '1samue':'1 Samuel',
   '1samuel':'1 Samuel',
   '2s':'2 Samuel',
   '2sa':'2 Samuel',
   '2sam':'2 Samuel',
   '2samu':'2 Samuel',
   '2samue':'2 Samuel',
   '2samuel':'2 Samuel',
   '1k':'1 Kings',
   '1ki':'1 Kings',
   '1kin':'1 Kings',
   '1king':'1 Kings',
   '1kings':'1 Kings',
   '2k':'2 Kings',
   '2ki':'2 Kings',
   '2kin':'2 Kings',
   '2king':'2 Kings',
   '2kings':'2 Kings',
   '1ch':'1 Chronicles',
   '1chr':'1 Chronicles',
   '1chro':'1 Chronicles',
   '1chron':'1 Chronicles',
   '1chroni':'1 Chronicles',
   '1chronic':'1 Chronicles',
   '1chronicl':'1 Chronicles',
   '1chronicle':'1 Chronicles',
   '1chronicles':'1 Chronicles',
   '2ch':'2 Chronicles',
   '2chr':'2 Chronicles',
   '2chro':'2 Chronicles',
   '2chron':'2 Chronicles',
   '2chroni':'2 Chronicles',
   '2chronic':'2 Chronicles',
   '2chronicl':'2 Chronicles',
   '2chronicle':'2 Chronicles',
   '2chronicles':'2 Chronicles',
   'ezr':'Ezra',
   'ezra':'Ezra',
   'ne':'Nehemiah',
   'neh':'Nehemiah',
   'nehe':'Nehemiah',
   'nehem':'Nehemiah',
   'nehemi':'Nehemiah',
   'nehemia':'Nehemiah',
   'nehemiah':'Nehemiah',
   'es':'Esther',
   'est':'Esther',
   'esth':'Esther',
   'esthe':'Esther',
   'esther':'Esther',
   'job':'Job',
   'ps':'Psalms',
   'psa':'Psalms',
   'psal':'Psalms',
   'psalm':'Psalms',
   'psalms':'Psalms',
   'pr':'Proverbs',
   'pro':'Proverbs',
   'prov':'Proverbs',
   'prove':'Proverbs',
   'prover':'Proverbs',
   'proverb':'Proverbs',
   'proverbs':'Proverbs',
   'ec':'Ecclesiastes',
   'ecc':'Ecclesiastes',
   'eccl':'Ecclesiastes',
   'eccle':'Ecclesiastes',
   'eccles':'Ecclesiastes',
   'ecclesi':'Ecclesiastes',
   'ecclesia':'Ecclesiastes',
   'ecclesias':'Ecclesiastes',
   'ecclesiast':'Ecclesiastes',
   'ecclesiaste':'Ecclesiastes',
   'ecclesiastes':'Ecclesiastes',
   's':'Song of Solomon',
   'so':'Song of Solomon',
   'son':'Song of Solomon',
   'song':'Song of Solomon',
   'songo':'Song of Solomon',
   'songof':'Song of Solomon',
   'songofs':'Song of Solomon',
   'songofso':'Song of Solomon',
   'songofsol':'Song of Solomon',
   'songofsolo':'Song of Solomon',
   'songofsolom':'Song of Solomon',
   'songofsolomo':'Song of Solomon',
   'songofsolomon':'Song of Solomon',
   'i':'Isaiah',
   'is':'Isaiah',
   'isa':'Isaiah',
   'isai':'Isaiah',
   'isaia':'Isaiah',
   'isaiah':'Isaiah',
   'je':'Jeremiah',
   'jer':'Jeremiah',
   'jere':'Jeremiah',
   'jerem':'Jeremiah',
   'jeremi':'Jeremiah',
   'jeremia':'Jeremiah',
   'jeremiah':'Jeremiah',
   'la':'Lamentations',
   'lam':'Lamentations',
   'lame':'Lamentations',
   'lamen':'Lamentations',
   'lament':'Lamentations',
   'lamenta':'Lamentations',
   'lamentat':'Lamentations',
   'lamentati':'Lamentations',
   'lamentatio':'Lamentations',
   'lamentation':'Lamentations',
   'lamentations':'Lamentations',
   'eze':'Ezekiel',
   'ezek':'Ezekiel',
   'ezeki':'Ezekiel',
   'ezekie':'Ezekiel',
   'ezekiel':'Ezekiel',
   'da':'Daniel',
   'dan':'Daniel',
   'dani':'Daniel',
   'danie':'Daniel',
   'daniel':'Daniel',
   'ho':'Hosea',
   'hos':'Hosea',
   'hose':'Hosea',
   'hosea':'Hosea',
   'joe':'Joel',
   'joel':'Joel',
   'am':'Amos',
   'amo':'Amos',
   'amos':'Amos',
   'o':'Obadiah',
   'ob':'Obadiah',
   'oba':'Obadiah',
   'obad':'Obadiah',
   'obadi':'Obadiah',
   'obadia':'Obadiah',
   'obadiah':'Obadiah',
   'jon':'Jonah',
   'jona':'Jonah',
   'jonah':'Jonah',
   'mi':'Micah',
   'mic':'Micah',
   'mica':'Micah',
   'micah':'Micah',
   'na':'Nahum',
   'nah':'Nahum',
   'nahu':'Nahum',
   'nahum':'Nahum',
   'hk':'Habakkuk',
   'hab':'Habakkuk',
   'haba':'Habakkuk',
   'habak':'Habakkuk',
   'habakk':'Habakkuk',
   'habakku':'Habakkuk',
   'habakkuk':'Habakkuk',
   'zp':'Zephaniah',
   'zep':'Zephaniah',
   'zeph':'Zephaniah',
   'zepha':'Zephaniah',
   'zephan':'Zephaniah',
   'zephani':'Zephaniah',
   'zephania':'Zephaniah',
   'zephaniah':'Zephaniah',
   'hag':'Haggai',
   'hagg':'Haggai',
   'hagga':'Haggai',
   'haggai':'Haggai',
   'zc':'Zechariah',
   'zec':'Zechariah',
   'zech':'Zechariah',
   'zecha':'Zechariah',
   'zechar':'Zechariah',
   'zechari':'Zechariah',
   'zecharia':'Zechariah',
   'zechariah':'Zechariah',
   'mal':'Malachi',
   'mala':'Malachi',
   'malac':'Malachi',
   'malach':'Malachi',
   'malachi':'Malachi',
   'mat':'Matthew',
   'matt':'Matthew',
   'matth':'Matthew',
   'matthe':'Matthew',
   'matthew':'Matthew',
   'mr':'Mark',
   'mar':'Mark',
   'mark':'Mark',
   'lu':'Luke',
   'luk':'Luke',
   'luke':'Luke',
   'joh':'John',
   'john':'John',
   'ac':'Acts',
   'act':'Acts',
   'acts':'Acts',
   'rm':'Romans',
   'ro':'Romans',
   'rom':'Romans',
   'roma':'Romans',
   'roman':'Romans',
   'romans':'Romans',
   '1co':'1 Corinthians',
   '1cor':'1 Corinthians',
   '1cori':'1 Corinthians',
   '1corin':'1 Corinthians',
   '1corint':'1 Corinthians',
   '1corinth':'1 Corinthians',
   '1corinthi':'1 Corinthians',
   '1corinthia':'1 Corinthians',
   '1corinthian':'1 Corinthians',
   '1corinthians':'1 Corinthians',
   '2co':'2 Corinthians',
   '2cor':'2 Corinthians',
   '2cori':'2 Corinthians',
   '2corin':'2 Corinthians',
   '2corint':'2 Corinthians',
   '2corinth':'2 Corinthians',
   '2corinthi':'2 Corinthians',
   '2corinthia':'2 Corinthians',
   '2corinthian':'2 Corinthians',
   '2corinthians':'2 Corinthians',
   'ga':'Galatians',
   'gal':'Galatians',
   'gala':'Galatians',
   'galat':'Galatians',
   'galati':'Galatians',
   'galatia':'Galatians',
   'galatian':'Galatians',
   'galatians':'Galatians',
   'ep':'Ephesians',
   'eph':'Ephesians',
   'ephe':'Ephesians',
   'ephes':'Ephesians',
   'ephesi':'Ephesians',
   'ephesia':'Ephesians',
   'ephesian':'Ephesians',
   'ephesians':'Ephesians',
   'phili':'Philippians',
   'philip':'Philippians',
   'philipp':'Philippians',
   'philippi':'Philippians',
   'philippia':'Philippians',
   'philippian':'Philippians',
   'philippians':'Philippians',
   'c':'Colossians',
   'co':'Colossians',
   'col':'Colossians',
   'colo':'Colossians',
   'colos':'Colossians',
   'coloss':'Colossians',
   'colossi':'Colossians',
   'colossia':'Colossians',
   'colossian':'Colossians',
   'colossians':'Colossians',
   '1th':'1 Thessalonians',
   '1the':'1 Thessalonians',
   '1thes':'1 Thessalonians',
   '1thess':'1 Thessalonians',
   '1thessa':'1 Thessalonians',
   '1thessal':'1 Thessalonians',
   '1thessalo':'1 Thessalonians',
   '1thessalon':'1 Thessalonians',
   '1thessaloni':'1 Thessalonians',
   '1thessalonia':'1 Thessalonians',
   '1thessalonian':'1 Thessalonians',
   '1thessalonians':'1 Thessalonians',
   '2th':'2 Thessalonians',
   '2the':'2 Thessalonians',
   '2thes':'2 Thessalonians',
   '2thess':'2 Thessalonians',
   '2thessa':'2 Thessalonians',
   '2thessal':'2 Thessalonians',
   '2thessalo':'2 Thessalonians',
   '2thessalon':'2 Thessalonians',
   '2thessaloni':'2 Thessalonians',
   '2thessalonia':'2 Thessalonians',
   '2thessalonian':'2 Thessalonians',
   '2thessalonians':'2 Thessalonians',
   '1ti':'1 Timothy',
   '1tim':'1 Timothy',
   '1timo':'1 Timothy',
   '1timot':'1 Timothy',
   '1timoth':'1 Timothy',
   '1timothy':'1 Timothy',
   '2ti':'2 Timothy',
   '2tim':'2 Timothy',
   '2timo':'2 Timothy',
   '2timot':'2 Timothy',
   '2timoth':'2 Timothy',
   '2timothy':'2 Timothy',
   't':'Titus',
   'tt':'Titus',
   'ti':'Titus',
   'tit':'Titus',
   'titu':'Titus',
   'titus':'Titus',
   'phile':'Philemon',
   'philem':'Philemon',
   'philemo':'Philemon',
   'philemon':'Philemon',
   'he':'Hebrews',
   'heb':'Hebrews',
   'hebr':'Hebrews',
   'hebre':'Hebrews',
   'hebrew':'Hebrews',
   'hebrews':'Hebrews',
   'ja':'James',
   'jam':'James',
   'jame':'James',
   'james':'James',
   '1p':'1 Peter',
   '1pe':'1 Peter',
   '1pet':'1 Peter',
   '1pete':'1 Peter',
   '1peter':'1 Peter',
   '2p':'2 Peter',
   '2pe':'2 Peter',
   '2pet':'2 Peter',
   '2pete':'2 Peter',
   '2peter':'2 Peter',
   '1j':'1 John',
   '1jo':'1 John',
   '1joh':'1 John',
   '1john':'1 John',
   '2j':'2 John',
   '2jo':'2 John',
   '2joh':'2 John',
   '2john':'2 John',
   '3':'3 John',
   '3j':'3 John',
   '3jo':'3 John',
   '3joh':'3 John',
   '3john':'3 John',
   'jude':'Jude',
   'rv':'Revelation',
   're':'Revelation',
   'rev':'Revelation',
   'reve':'Revelation',
   'revel':'Revelation',
   'revela':'Revelation',
   'revelat':'Revelation',
   'revelati':'Revelation',
   'revelatio':'Revelation',
   'revelation':'Revelation',
}